config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "profiles#index"

  # PROFILE ROUTES
  get "/profiles/new", to: "profiles#new"
  get "/profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
  patch "/profiles/:id", to: "profiles#update"
  get "/profiles/:id", to: "profiles#show", as: 'profile'
  post "/profiles", to: "profiles#create"
  delete "/profiles/:id", to: "profiles#destroy", as: 'destroy_profile'
  
  # MESSAGE ROUTES
  get "/profiles/:id/messages/new", to: "messages#new", as: "messages_new"
  post "/profiles/:id/messages", to: "messages#create", as: 'create_message'
  patch "/messages/:id", to: "messages#update", as: 'update_message'
  delete "/messages/:id", to: "messages#destroy", as: 'destroy_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/major.rb
class Major < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: :sender_id
  belongs_to :receiver, class_name: "User", foreign_key: :receiver_id

  validates :content , presence: :true, length: { maximum: 200,
    too_long: "%{count} characters is the maximum allowed" }
  
  scope :unseen, -> { where(seen: false)}
  scope :seen, -> { where(seen: true)}

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :profile_qualifications, dependent: :destroy
  has_many :qualifications, through: :profile_qualifications

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :blurb, length: { maximum: 500,
    too_long: "%{count} characters is the maximum allowed" }

  has_one_attached :picture

  def has_qualification?(qualification_id)
    begin
      return true if qualifications.find(qualification_id)
    rescue
      return false
    end
  end
  
  def has_any_qualifications?
    begin
      return profile_qualifications.length > 0
    rescue
      return false
    end
  end

  def get_qualification_major(qualification_id)
    begin
      return profile_qualifications.find_by(qualification_id: qualification_id).major.id
    rescue
      return 0
    end
  end

  def users_profile?()
    begin
      current_user.id == user_id
    rescue => exception
      false
    end
  end

  def has_phone?
    begin
      phone != nil
      return true
    rescue
      false
    end
  end

end

app/models/profile_qualification.rb
class ProfileQualification < ApplicationRecord
  belongs_to :profile
  belongs_to :qualification
  belongs_to :major
end

app/models/qualification.rb
class Qualification < ApplicationRecord
  has_many :profile_qualifications, dependent: :destroy
  has_many :profiles, through: :profile_qualifications

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  # after_create :set_role
  rolify

  has_one :profile

  has_many :messages_received, class_name: "Message", foreign_key: :receiver
  has_many :messages_sent, class_name: "Message", foreign_key: :sender

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def set_role
    # set a default role but only if it's empty
    self.add_role(:default_user) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def new
    @message = Message.new()
  end

  def create
  #   @message = Message.new(profile_params)
  #   @message.seen = false
  #  begin 
  #     @message.save!
  #     redirect_to root_path
  #   rescue
  #     flash.now[:errors] = @message.errors.messages.values.flatten
  #     render 'new'
  #   end
    @message = Message.new(profile_params)
    @message.seen = false
    @message.save!
    redirect_to root_path
  end

  def update
  end

  def destroy
    @profile.destroy
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:sender_id, :receiver_id, :seen, :content)
  end

  def prep_message
    @message = Message.find(params[:id])
  end

  def check_auth
    authorize @message || Message
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!  

  def new
    @message = Message.new()
  end

  def create
  #   @message = Message.new(profile_params)
  #   @message.seen = false
  #  begin 
  #     @message.save!
  #     redirect_to root_path
  #   rescue
  #     flash.now[:errors] = @message.errors.messages.values.flatten
  #     render 'new'
  #   end
    @message = Message.new(message_params)
    @message.sender = current_user
    @message.receiver_id = Profile.find(params[:id]).user_id
    @message.seen = false
    begin
      @message.save!
      redirect_to root_path
    rescue
      flash.now[:errors] = @message.errors.messages.values.flatten
      render 'new'
    end
   
  end

  def update
    Message.find(params[:id]).update(seen: true)
  end

  def destroy
    Message.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:sender_id, :receiver_id, :seen, :content, :id)
  end

  def prep_message
    @message = Message.find(params[:id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :prep_profile, only: [:show, :edit, :update, :destroy]
  before_action :prep_qualifications, only: [:edit, :new]
  before_action :authenticate_user!, except: :index
  before_action :check_auth

  def index
    @profiles = Profile.all
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    params[:profile_qualifications].each do | key, value|
      if value == "1"
        @profile.profile_qualifications.new(qualification_id:key, major_id:params[key][:qualification_major])
      end
    end
    begin
      @profile.save!
      redirect_to root_path
    rescue => exception
      flash.now[:errors] = @book.errors.messages.values.flatten
      render 'new'
    end
  end

  def edit
    render :edit
  end

  def update
    @profile.update(profile_params)
    ProfileQualification.destroy_by(profile_id:@profile.id)
    params[:profile_qualifications].each do | key, value|
      if value == "1"
        @profile.profile_qualifications.new(qualification_id:key, major_id:params[key][:qualification_major])
      end
    end
    @profile.save
    redirect_to profile_path(@profile.id)
  end

  def destroy
    @profile.destroy
    redirect_to root_path
  end  

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :blurb, :phone, :picture, :qualification_ids, :contactable)
  end

  def prep_profile
    @profile = Profile.find(params[:id])
    current_index = Profile.all.index(@profile)
    
    @next_profile_id = Profile.all[(current_index + 1) % Profile.all.count].id
    @previous_profile_id = Profile.all[(current_index - 1) % Profile.all.count].id
  end

  def prep_qualifications
    @qualifications = Qualification.all
    @majors = Major.all
  end

  def check_auth
    authorize @profile || Profile
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/application/_nav.html.erb
<ul class="nav nav-tabs d-flex justify-content-center">
  <li role="presentation" class="p-1">
    <%= link_to "Home", root_path, class:"btn" %>
  </li>
    <% if user_signed_in? %>
      <% if current_user.profile %>
        <li role="presentation" class="p-1">
          <%= link_to "My Accompanist Profile", profile_path(current_user.profile.id), class:"btn" %>
        </li>
      <% else %>
        <li role="presentation" class="p-1">
          <%= link_to "Create Accompanist Profile", profiles_new_path, class:"btn" %>
        </li>
      <% end %>
      <li role="presentation" class="p-1">
        <%= link_to "Logout(#{current_user.email})", destroy_user_session_path, method: :delete, class:"btn" %>
      </li>
    <% else %>
      <li role="presentation" class="p-1">
        <%= link_to 'Login', new_user_session_path, class:"btn" %>
      </li>
      <li role="presentation" class="p-1">
        <%= link_to 'Sign Up', new_user_registration_path, class:"btn" %>
      </li>

    <% end %>
</ul>

app/views/application/_title.html.erb
<div class="container-fluid hero-image">
  <%= image_tag "GoldBlackLogowithouticon.png", class:"img-fluid" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/message/new.html.erb
<h1>New message</h1>
<%= form_with model: @message do |f| %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p>
      <%= f.label :content %>
      <%= f.text_field :content, placeholder: "Leave your message for the accompanist here..."%>
    </p>
    <p>
    <%= f.submit %>
    </p>
  <% end %>

app/views/messages/_new_message_form.html.erb
<div>
  <%= form_with model: @message, url: create_message_path(params[:id]) do |f| %>
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <div class="field">
      <%= f.label "Message" %><br />
      <%= f.text_area :content, placeholder: "Insert message here...", size: "60x8"%>
    </div>
    <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/messages/new.html.erb
<div class="container-sm">
  <p>
    Leave a message for <%= Profile.find(params[:id]).first_name.capitalize() %> with information as to why you would like to make contact, make it as detailed as you can in less than 200 characters. Please note that an accompanist may or may not contact you back.
  </p>
  <%= render partial: "new_message_form" %>
</div>

app/views/profiles/_accompanist_cards.html.erb
<div class="card-group container-sm" >
  <% @profiles.each do | p | %>
    <div class="card m-1 border" style="max-width: 200px; min-width: 200px;">
        <% if p.picture.attached? %>
          <%= cl_image_tag p.picture.key, cloud_name: "dbsmyugus", crop: :scale, width: 200, height: 200, class: 'card-img-top image-fluid'%>
        <% else %>
          <%= image_tag "icon-white-gold-blabkbg.jpg", width: 200, height: 200, class: 'card-img-top image-fluid' %>
        <% end %>
      <div class="card-body position-relative">
        <h5 class="card-title">
          <%= "#{p.first_name} #{p.last_name}" %>
        </h5>
        <h6 class="card-title qual-count">
          <%= "#{p.profile_qualifications.length} qualifications" if p.has_any_qualifications? %>
        </h6>
        <p class="card-text">
          <% if p.blurb != nil %>
            <%= p.blurb.length > 60 ? "#{p.blurb[0..55]}..." : "#{p.blurb}" %>
          <% end %>
        </p>
        <% if current_user == nil %>
          <%= link_to "sign in to learn more", profile_path(p.id), class: 'btn align-self-end' %>
        <% else %>
          <%= link_to "see profile", profile_path(p.id), class: 'btn align-self-end justify-self-center' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<div class="container-sm">
  <%= form_with model: @profile do |f| %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </p>
    <p>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </p>
    <p>
      <%= f.label :phone %>
      <%= f.telephone_field :phone %>
    </p>
    <p>
      <%= f.label "Contact details visible?" %>
      <%= f.check_box :contactable, checked: @profile.contactable %>
    </p>
    <p>
      <%= f.label "About me:" %><br />
      <%= f.text_area :blurb, placeholder: "Tell people who you are, your experience and why you would be a great choice for them. Max 500 characters.", size: "60x8" %>
    </p>
    <p>
      <%= f.label "Profile Picture" %>
      <%= f.file_field :picture, placeholder: "title"%>
    </p>
    <p>
       <%= fields_for :profile_qualifications do |nested_form| %>
        <% @qualifications.each do |q| %>
        <div>
            <%= nested_form.label q.name %>
            <%= nested_form.check_box q.id, checked: @profile.has_qualification?(q.id) %>
            <%= fields_for "#{q.id}" do |nf| %>
              <%= nf.collection_select :qualification_major, @majors, :id, :name, selected: @profile.get_qualification_major(q.id) %>
            <% end%>
        </div>   
        <% end %>
      <% end %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/profiles/index.html.erb
<div class="container-sm">
  <div class="header sticky-top">
    <%= render "title" %>
    <%= render "nav" %>
  </div>
  <div id="welcome">
      <% if flash[:errors] %>
        <section id="errors">
          <% flash[:errors].each do |error| %>
            <p><%= error %></p>
          <% end %>
        </section>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <% if flash[:notice] %>
        <p class="notice"><%= notice %></p>
      <% end %>
    <p id="welcome-message" >Welcome! Here you'll find all our available accompanists.</p>
    <% if user_signed_in? %>
      <% if current_user.profile == nil %>
        <p>
        If YOU are an accompanist, <%= link_to "setup your accompanist profile", profiles_new_path %>.
        </p>
      <% end %>
    <% else %>
      <p><%= link_to "Sign in", new_user_session_path %> to make contact!</p>
    <% end %>
  </div>
<%= render partial: 'accompanist_cards' %>
</div>

app/views/profiles/new.html.erb
<div class="container-sm">
  <%= form_with model: @profile do |f| %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "first name"%>
    </p>
    <p>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: "last name"%>
    </p>
    <p>
      <%= f.label :phone %>
      <%= f.telephone_field :phone, placeholder: "mobile or home phone"%>
    </p>
    <p>
      <%= f.label "Contact details visible?" %>
      <%= f.check_box :contactable %>
    </p>
    <p>
      <%= f.label "Profile Picture" %>
      <%= f.file_field :picture, placeholder: "profile picture"%>
    </p>
    <p>
      <%= f.label "About me:" %><br />
      <%= f.text_area :blurb, placeholder: "Tell people who you are, your experience and why you would be a great choice for them. Max 500 characters.", size: "60x8" %>
    </p>
    <p>
      <%= fields_for :profile_qualifications do |nested_form| %>
        <% @qualifications.each do |q| %>
          <div>
              <%= nested_form.label q.name %>
              <%= nested_form.check_box q.id %>
              <%= fields_for "#{q.id}" do |nf| %>
                <%= nf.collection_select :qualification_major, @majors, :id, :name %>
              <% end%>
          </div>   
        <% end%>
      <% end %>
    </p>
    <p>
    <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container-sm" id="profile">
  <div class="row sticky-top" id="profile-header">
    <div class="col-sm-auto">
      <%= image_tag "GoldBlackAMicon.png", width: 150, id:"show-icon" %>
    </div>
    <div class="col-sm">
      <h1 id="show-acc-name">
        <%= @profile.first_name %>
        <%= @profile.last_name %>
      </h1>
      <nav>
        <%= link_to "<< previous", profile_path(@next_profile_id), class:"btn" %>
        |
        <%= link_to "home", root_path, class:"btn" %>
        |
        <%= link_to "next >>", profile_path(@previous_profile_id), class:"btn" %>
      </nav>
    </div>
  </div>
  <div id="profile-body">
    <div class="row">
      <div class="col-sm-auto">
        <% if @profile.picture.attached? %>
          <%= cl_image_tag @profile.picture.key, cloud_name: "dbsmyugus", crop: :scale, width: 150 %>
        <% else %>
          <%= image_tag "load_profile.png", width: 150, class:"image-fluid"%>
        <% end %>
      </div>
      <div class="col-sm">
        <% if @profile.has_any_qualifications? %>
          <h5> Qualifications: </h5>
          <ul>
            <% @profile.profile_qualifications.each do |qual| %>
              <li>
                <%= Qualification.find(qual.qualification_id).name %>
                <%= Major.find(qual.major_id).name == "Undisclosed" ? "" : " in #{ Major.find(qual.major_id).name }" %>
              </li>
            <% end %>
          </ul>
          <% else %>
            <p class="announce">This accompanist has listed NO qualifications and thus, may not be appropriate.</p>
        <% end %>
        <% if @profile.contactable %>
          <p><%= " email: #{@profile.user.email}" %><%= " | phone: #{@profile.phone}" if @profile.has_phone?%></p>
        <% else %>
          <%= link_to "make contact", messages_new_path, class:"btn" %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <% if current_user.has_role?(:admin) %>
          <h5 class="announce">NOTE: CURRENTLY SIGNED IN AS ADMIN </h5>
          <%= link_to "ADMIN EDIT", edit_profile_path(@profile.id) %>
          <%= link_to "ADMIN DELETE", destroy_profile_path(@profile.id), class:"btn", message: "Are you sure you wish to remove this profile?", method: :delete %>
        <% end %>
        <h5>About me:</h5>
        <p><%= @profile.blurb %></p>
      </div>
    </div>

  <div class="row">
    <div class="col">
      <% if @profile.user_id == current_user.id %>
        <h4 class="announce">My Profile 
        <%= link_to "edit", edit_profile_path(@profile.id), class:"btn" %>
        <%= link_to "remove", destroy_profile_path(@profile.id), class:"btn", message: "Are you sure you wish to remove your profile?", method: :delete %>
        </h4>
        <hr />
        <% if @profile.has_any_qualifications? == false %>
          <p class="announce">Notice: please load qualifications as soon as possible.</p>
        <% end %>
      <% end %>
    </div>
  </div>
  <% if policy(@profile).update? %>
    <div class="row">
      <div class="col">
        <h5>My contact requests</h5>
        <% if @profile.user.messages_received.unseen.count == 0 %>
          <p>You currently have no contact requests.</p>
        <% else %>
          <table>
            <% @profile.user.messages_received.unseen.each do |msg| %>
              <tr>
                <td class="email"><%= msg.sender.email %></td>
                <td class="content"><%= msg.content %></td>
                <td><%= link_to "clear", update_message_path(msg.id), method: :patch, class:"btn" %></td>
                <% if current_user.has_role?(:admin) %>
                  <td><%= link_to "DELETE MESSAGE(ADMIN)", destroy_message_path(msg.id), method: :patch %></td>
                <% end %>
              </tr>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>
  <% end %>
</div>